import { Restaurant } from "./types";

/**
 * Menú del restaurante demo.
 *
 * Este archivo es la única fuente de verdad: alimenta el menú del cliente,
 * el visor 3D/AR y el asistente. Si el asistente ha de saber algo de un
 * plato, va aquí — no en el código del chatbot.
 *
 * Los modelos 3D se sirven desde /public/models. Están modelados a escala
 * real en metros (plato de entrada 21 cm, fuerte 27 cm, postre 18 cm,
 * copa 9 cm), que es lo que hace que en AR aparezcan del tamaño que
 * tendrán sobre la mesa. Para un restaurante real se reemplazan por
 * escaneos de los platos verdaderos (Polycam o KIRI Engine exportan .glb)
 * cambiando solo la ruta de `model3d`.
 *
 * El orden dentro de cada categoría no es casual: los platos de mejor
 * margen van en las dos primeras posiciones y en la última, que es donde
 * más se fija la vista.
 */

const IMG = (id: string, w = 1200) =>
  `https://images.unsplash.com/${id}?w=${w}&q=75&auto=format&fit=crop`;

const M = (id: string, ancho: number, alto: number) => ({
  glb: `/models/${id}.glb`,
  medidas: { ancho, alto },
});

export const restaurant: Restaurant = {
  slug: "fogon-barines",
  name: "Fogón Barinés",
  tagline: "Cocina de brasa y sabores de los Llanos",
  logoInitial: "F",
  tableCount: 12,
  categories: [
    {
      id: "entradas",
      name: "Para empezar",
      nav: "Entradas",
      intro: "Frescos y de cuchara",
    },
    {
      id: "fuertes",
      name: "De la brasa",
      nav: "Brasa",
      intro: "Fuego lento y leña",
    },
    { id: "postres", name: "Para cerrar", nav: "Postres" },
    { id: "bebidas", name: "De la barra", nav: "Barra" },
  ],
  dishes: [
    {
      id: "aguacate-camarones",
      name: "Aguacate relleno con camarones al ajillo",
      description:
        "Aguacate criollo abierto al momento, relleno de camarones salteados en ajo y mantequilla de la casa.",
      price: 8.5,
      image: IMG("photo-1600335895229-6e75511892c8"),
      category: "entradas",
      tags: ["plato estrella"],
      portion: "Un aguacate entero · una persona",
      model3d: M("aguacate-camarones", 21, 4.7),
      available: true,
      ingredientes: [
        "aguacate criollo",
        "camarones",
        "ajo",
        "mantequilla",
        "ají dulce",
        "cilantro",
        "limón",
      ],
      alergenos: ["mariscos", "lacteos"],
      dietas: ["sin gluten"],
      picante: 1,
      picanteOpcional: true,
      minutos: 12,
      personas: 1,
      perfil: ["cremoso", "mantecoso", "aromático", "tibio sobre frío"],
      combina: ["coctel-casa", "lomo-parrilla"],
      nota: "El aguacate se abre al momento de pedirlo, por eso no se pide sin camarones: se oxida.",
      alias: ["aguacate", "palta", "aguacate relleno", "camarones al ajillo"],
      gramos: 319,
      macros: { kcal: 500, proteina: 24, carbohidratos: 21, grasa: 39, fibra: 14 },
      ajustes: ["sin picante", "sin cilantro"],
    },
    {
      id: "ceviche-camarones",
      name: "Ceviche de camarones estilo Barinas",
      description:
        "Camarones curados en limón con ají dulce, cebolla morada y cilantro. Se sirve bien frío, en su propio jugo.",
      price: 7.0,
      image: IMG("photo-1626663011519-b42e5ee10056"),
      category: "entradas",
      tags: ["más pedido"],
      portion: "250 g · una persona",
      model3d: M("ceviche-camarones", 15, 5.5),
      available: true,
      ingredientes: [
        "camarones",
        "limón",
        "ají dulce",
        "cebolla morada",
        "cilantro",
        "sal marina",
      ],
      alergenos: ["mariscos"],
      dietas: ["sin gluten", "sin lacteos"],
      picante: 1,
      picanteOpcional: true,
      minutos: 8,
      personas: 1,
      perfil: ["cítrico", "fresco", "ligero", "frío"],
      combina: ["coctel-casa", "lomo-parrilla", "costillas-bbq"],
      nota: "Lo más ligero del menú y lo que más sale. Buena entrada antes de algo de la brasa.",
      alias: ["ceviche", "cebiche", "seviche"],
      gramos: 356,
      macros: { kcal: 280, proteina: 61, carbohidratos: 9, grasa: 1, fibra: 1 },
      ajustes: ["sin picante", "sin cebolla", "sin cilantro", "media porción"],
    },
    {
      id: "ensalada-casa",
      name: "Ensalada fresca de la casa",
      description:
        "Vegetales de estación, queso de mano llanero, tomate confitado y vinagreta de papelón.",
      price: 5.5,
      image: IMG("photo-1512621776951-a57141f2eefd"),
      category: "entradas",
      tags: ["vegetariano"],
      portion: "Alcanza para compartir entre dos",
      model3d: M("ensalada-casa", 21, 4.3),
      available: true,
      ingredientes: [
        "lechugas de estación",
        "queso de mano",
        "tomate confitado",
        "vinagreta de papelón",
        "cebollín",
      ],
      alergenos: ["lacteos"],
      dietas: ["vegetariano", "sin gluten"],
      picante: 0,
      minutos: 6,
      personas: 2,
      perfil: ["fresco", "dulce y ácido", "crujiente"],
      combina: ["lomo-parrilla", "costillas-bbq", "hamburguesa-premium"],
      nota: "Se puede pedir sin queso para volverla vegana; la vinagreta no lleva lácteos.",
      alias: ["ensalada", "ensalada de la casa", "vegetales"],
      gramos: 290,
      macros: { kcal: 340, proteina: 12, carbohidratos: 17, grasa: 26, fibra: 4 },
      ajustes: [
        "sin queso (queda vegana)",
        "vinagreta aparte",
        "porción individual",
      ],
    },

    {
      id: "lomo-parrilla",
      name: "Lomo a la parrilla con chimichurri",
      description:
        "Corte grueso de lomo sellado sobre leña, al término que pidas, con chimichurri de la casa y yuca frita.",
      price: 14.0,
      image: IMG("photo-1600891964092-4316c288032e"),
      category: "fuertes",
      tags: ["más pedido"],
      portion: "320 g · una persona",
      model3d: M("lomo-parrilla", 27, 5.6),
      available: true,
      ingredientes: [
        "lomo de res",
        "chimichurri",
        "yuca frita",
        "sal en grano",
        "aceite de oliva",
      ],
      alergenos: [],
      dietas: ["sin gluten", "sin lacteos"],
      picante: 0,
      minutos: 22,
      personas: 1,
      perfil: ["ahumado", "jugoso", "herbal", "contundente"],
      combina: ["ensalada-casa", "coctel-casa", "torta-chocolate"],
      nota: "El término se pide al ordenar. Es el corte más grueso del menú, tarda unos 22 minutos.",
      alias: ["lomo", "carne", "steak", "bife", "parrilla", "res"],
      gramos: 463,
      macros: { kcal: 1060, proteina: 95, carbohidratos: 50, grasa: 52, fibra: 3 },
      ajustes: [
        "término al gusto",
        "sin chimichurri",
        "cambiar la yuca por ensalada",
      ],
    },
    {
      id: "hamburguesa-premium",
      name: "Hamburguesa Fogón",
      description:
        "Carne molida en casa, queso ahumado, tocineta crocante, cebolla caramelizada y salsa de la casa.",
      price: 9.5,
      image: IMG("photo-1550547660-d9450f859349"),
      category: "fuertes",
      tags: ["más pedido"],
      portion: "250 g de carne · papas incluidas",
      model3d: M("hamburguesa-premium", 27, 11.2),
      available: true,
      ingredientes: [
        "carne de res molida",
        "pan brioche",
        "queso ahumado",
        "tocineta",
        "cebolla caramelizada",
        "salsa de la casa",
        "papas fritas",
      ],
      alergenos: ["gluten", "lacteos", "huevo"],
      picante: 0,
      minutos: 15,
      personas: 1,
      perfil: ["ahumado", "salado", "jugoso", "contundente"],
      combina: ["coctel-casa", "ensalada-casa"],
      nota: "Viene con papas incluidas, no hace falta pedir acompañante aparte.",
      alias: ["hamburguesa", "burger", "burguer", "hamburgesa"],
      gramos: 555,
      macros: { kcal: 1620, proteina: 94, carbohidratos: 91, grasa: 95, fibra: 7 },
      ajustes: [
        "sin tocineta",
        "sin queso",
        "sin cebolla",
        "cambiar las papas por ensalada",
      ],
    },
    {
      id: "pasta-pesto",
      name: "Pasta al pesto con camarones",
      description:
        "Pasta fresca del día en pesto de albahaca, con camarones salteados y lascas de parmesano.",
      price: 11.0,
      image: IMG("photo-1627042633145-b780d842ba45"),
      category: "fuertes",
      portion: "Porción generosa · una persona",
      model3d: M("pasta-pesto", 27, 6.4),
      available: true,
      ingredientes: [
        "pasta fresca",
        "pesto de albahaca",
        "camarones",
        "parmesano",
        "piñones",
        "ajo",
      ],
      alergenos: ["gluten", "lacteos", "mariscos", "frutos secos", "huevo"],
      picante: 0,
      minutos: 16,
      personas: 1,
      perfil: ["cremoso", "herbal", "salado"],
      combina: ["ensalada-casa", "coctel-casa", "torta-chocolate"],
      nota: "El pesto lleva piñones y parmesano; si hay alergia a frutos secos, este plato no aplica.",
      alias: ["pasta", "pesto", "espagueti", "tallarines", "fideos"],
      gramos: 348,
      macros: { kcal: 710, proteina: 43, carbohidratos: 61, grasa: 33, fibra: 4 },
      ajustes: ["sin camarones", "sin parmesano"],
    },
    {
      id: "costillas-bbq",
      name: "Costillas ahumadas BBQ",
      description:
        "Costillas de cerdo ahumadas seis horas, glaseadas en BBQ de papelón, con ensalada de papa.",
      price: 13.5,
      image: IMG("photo-1588168333986-5078d3ae3976"),
      category: "fuertes",
      portion: "400 g · una persona con buen apetito",
      model3d: M("costillas-bbq", 27, 4.2),
      available: false,
      ingredientes: [
        "costillas de cerdo",
        "salsa BBQ de papelón",
        "especias ahumadas",
        "ensalada de papa",
        "mayonesa",
      ],
      alergenos: ["huevo", "soya"],
      picante: 1,
      minutos: 18,
      personas: 1,
      perfil: ["ahumado", "dulce", "pegajoso", "contundente"],
      combina: ["ensalada-casa", "coctel-casa"],
      nota: "Se ahúman seis horas desde la madrugada; cuando se acaban, se acaban hasta el día siguiente.",
      alias: ["costillas", "costilla", "ribs", "bbq", "cerdo", "puerco"],
      gramos: 440,
      macros: { kcal: 1210, proteina: 74, carbohidratos: 35, grasa: 86, fibra: 2 },
      ajustes: ["salsa aparte", "media porción"],
    },

    {
      id: "torta-chocolate",
      name: "Torta de chocolate con ganache",
      description:
        "Bizcocho húmedo de chocolate con ganache y una pizca de sal de mar que levanta el dulce.",
      price: 4.5,
      image: IMG("photo-1602351447937-745cb720612f"),
      category: "postres",
      tags: ["vegetariano"],
      portion: "Una porción · alcanza para dos si es después de un fuerte",
      model3d: M("torta-chocolate", 18, 6.2),
      available: true,
      ingredientes: [
        "chocolate oscuro",
        "harina de trigo",
        "huevo",
        "mantequilla",
        "crema de leche",
        "sal de mar",
      ],
      alergenos: ["gluten", "lacteos", "huevo"],
      dietas: ["vegetariano"],
      picante: 0,
      minutos: 4,
      personas: 2,
      perfil: ["dulce", "intenso", "húmedo"],
      combina: ["coctel-casa"],
      nota: "Sale fría de nevera; si la prefieres tibia, se calienta un minuto, solo hay que avisar.",
      alias: ["torta", "postre", "chocolate", "pastel", "cake"],
      gramos: 120,
      macros: { kcal: 490, proteina: 6, carbohidratos: 52, grasa: 29, fibra: 3 },
      ajustes: ["tibia", "sin sal de mar", "con dos cucharas"],
    },

    {
      id: "coctel-casa",
      name: "Coctel de la casa",
      description:
        "Ron añejo llanero, papelón, limón y romero fresco quemado al momento. Hay versión sin alcohol.",
      price: 6.0,
      image: IMG("photo-1609951651556-5334e2706168"),
      category: "bebidas",
      model3d: M("coctel-casa", 9, 11.9),
      available: true,
      ingredientes: [
        "ron añejo",
        "papelón",
        "limón",
        "romero fresco",
        "hielo",
      ],
      alergenos: ["alcohol"],
      dietas: ["vegetariano", "sin gluten", "sin lacteos"],
      picante: 0,
      minutos: 5,
      personas: 1,
      perfil: ["dulce", "cítrico", "herbal", "aromático"],
      combina: ["ceviche-camarones", "lomo-parrilla", "costillas-bbq"],
      nota: "La versión sin alcohol cuesta lo mismo y lleva el mismo romero quemado.",
      alias: ["coctel", "cocktail", "trago", "bebida", "ron", "copa"],
      gramos: 97,
      macros: { kcal: 210, proteina: 0, carbohidratos: 24, grasa: 0, fibra: 0 },
      ajustes: ["sin alcohol", "sin hielo", "menos dulce"],
    },
  ],
};
